# -*- coding: utf-8 -*-
"""PlaneCrashDataAnalysisProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tm40NA-FhoNtd9b3Qma74OFQ63crF1Yy
"""

library(data.table) # import library
myDF <- fread("/content/commercialairplanecrashes.csv", header = TRUE) # assign the csv file to myDF
tail(myDF) # use the tail function for myDF when displaying the dataset

"""In the code above, we essentially inputted the library function and called it as a data table. After that we declared myDF and imported the commercialairplanecrashes.csv file."""

table(myDF$`Cause of Crash`) # made a table based off the different causes of crashes in the dataset

"""In the code above, we made a table based off the different causes of crashes in the dataset"""

table(myDF$`Cause Abbreviation`) # made a table with the abbreviation of every cause alongside the number of occurences per
# CI = Cargo Issues
# FA = Firefighting accident
# FS = Aircraft entered a flat spin
# GC = Landing gear collapse
# IN = Inconclusive
# LC = Lost control of aircraft
# LE = Pilot Landing error
# LF = Emergency landing failure
# ME = Mechanical error
# PP = Poor weather and pilot error
# SD = Plane shot down
# ST = Severe turbulence
# TE = Takeoff error
# UD = Uncontrolled decompression
# WC = Weather conditions

"""In the code above, we made a table with the abbreviation of every cause alongside the number of occurences per crash cause."""

# Set the margins of the plot area
par(mar = c(5, 5, 2, 1))  # Adjusts the margin sizes for the plot (bottom, left, top, right).

# Create a rainbow color palette for the bars
colors <- rainbow(length(table(myDF$`Cause Abbreviation`)))  # Generates a set of rainbow colors equal to the number of unique crash causes.

# Create a barplot showing the frequency of crash occurrences by cause
barplot(
  table(myDF$`Cause Abbreviation`),  # Creates a table counting the frequency of each unique crash cause in the dataset.
  main = "Frequency of Crash Occurrences",  # Sets the title of the barplot.
  xlab = "Cause of Crash",  # Labels the x-axis.
  ylab = "Frequency of Occurrence",  # Labels the y-axis.
  col = colors,  # Colors the bars using the rainbow palette created earlier.
  las = 2  # Rotates the x-axis labels by 90 degrees for better readability.
)

# CI = Cargo Issues
# FA = Firefighting accident
# FS = Aircraft entered a flat spin
# GC = Landing gear collapse
# IN = Inconclusive
# LC = Lost control of aircraft
# LE = Pilot Landing error
# LF = Emergency landing failure
# ME = Mechanical error
# PP = Poor weather and pilot error
# SD = Plane shot down
# ST = Severe turbulence
# TE = Takeoff error
# UD = Uncontrolled decompression
# WC = Weather conditions

"""The code generates a colorful barplot that visualizes the frequency of crash causes. Each bar represents a unique crash cause, with the height indicating how often it occurred. The use of rainbow colors helps differentiate between causes visually."""

# Create an index for each unique Cause Abbreviation
myDF$CauseIndex <- as.numeric(factor(myDF$`Cause Abbreviation`))  # Converts the unique crash causes to numeric indices.

# Create a scatter plot to visualize fatalities by crash cause
plot(
  myDF$Fatalities, myDF$CauseIndex,  # Plots Fatalities on the x-axis and CauseIndex on the y-axis.
  xlab = "Fatalities",  # Labels the x-axis as "Fatalities".
  ylab = "Cause of Crash",  # Labels the y-axis as "Cause of Crash".
  main = "Crash Chart",  # Sets the title of the plot.
  pch = 16,  # Specifies the plotting symbol (16 is a filled circle).
  col = "black",  # Sets the color of the points to black.
  xaxt = "n",  # Suppresses the x-axis ticks.
  yaxt = "n"  # Suppresses the y-axis ticks.
)

# Add unique labels to the y-axis
axis(
  2,  # Specifies the y-axis.
  at = unique(myDF$CauseIndex),  # Sets tick marks at the unique CauseIndex values.
  labels = unique(myDF$`Cause Abbreviation`),  # Uses the unique crash causes as labels.
  las = 2  # Rotates the labels to a vertical orientation for better readability.
)

# Add the default x-axis
axis(1)  # Draws the x-axis with default settings.

"""The resulting scatter plot shows crash causes (y-axis) against the number of fatalities (x-axis). Each point represents a crash, with its horizontal position determined by fatalities and its vertical position corresponding to its crash cause. The y-axis labels are the crash causes, making the chart easy to interpret."""

# Adjust margins for the plot
par(mar = c(5, 5, 5, 5))  # Sets the margins of the plot area (bottom, left, top, right).

# Create an index for each unique year
myDF$YearIndex <- as.numeric(factor(myDF$Year))  # Converts unique years to numeric indices for plotting.

# Create a scatter plot to visualize fatalities by year
plot(
  myDF$Fatalities, myDF$YearIndex,  # Plots Fatalities on the x-axis and YearIndex on the y-axis.
  xlab = "Fatalities",  # Labels the x-axis as "Fatalities".
  ylab = "Year",  # Labels the y-axis as "Year".
  main = "Crash Chart",  # Sets the title of the plot.
  pch = 16,  # Specifies the plotting symbol (16 is a filled circle).
  col = "black",  # Sets the color of the points to black.
  xaxt = "n",  # Suppresses the x-axis ticks.
  yaxt = "n"  # Suppresses the y-axis ticks.
)

# Add unique labels to the y-axis
axis(
  2,  # Specifies the y-axis.
  at = myDF$YearIndex,  # Places tick marks at the numeric indices of years.
  labels = myDF$Year,  # Uses the actual year values as labels for the tick marks.
  las = 2  # Rotates the labels to a vertical orientation for better readability.
)

# Add the default x-axis
axis(1)  # Draws the x-axis with default settings.

"""The resulting scatter plot shows the number of fatalities (x-axis) for each year (y-axis). Each point represents a crash, with its horizontal position determined by the number of fatalities and its vertical position corresponding to the year of occurrence. The years are clearly labeled on the y-axis."""

# Aggregate fatalities by year
aggregated_data <- aggregate(Fatalities ~ Year, data = myDF, sum)  # Summarizes the total number of fatalities for each year.

# Create a dot chart for yearly fatalities
dotchart(
  aggregated_data$Fatalities,  # Total fatalities for each year (x-axis values).
  labels = aggregated_data$Year,  # Labels for each year (y-axis values).
  main = "Yearly Fatalities",  # Sets the title of the chart.
  xlab = "Total Fatalities",  # Labels the x-axis as "Total Fatalities".
  ylab = "Year",  # Labels the y-axis as "Year".
  col = "black"  # Sets the color of the dots to black.
)

"""The resulting dot chart displays the total fatalities on the x-axis and the corresponding years on the y-axis. Each dot represents the total number of fatalities for a specific year. This visualization provides a clear view of trends in fatalities over time."""

# Adjust plot margins
par(mar = c(5, 5, 5, 5))  # Sets margins (bottom, left, top, right) for the bar plot.

# Create a bar plot of GDP per Capita by Country
barplot(
  myDF$`Country GDP per Capita`,  # GDP per Capita values for each country (y-axis values).
  names.arg = myDF$Country,  # Country names as x-axis labels.
  las = 2,  # Rotates the x-axis labels to a vertical orientation for readability.
  col = "black",  # Colors the bars black.
  main = "Country vs GDP per Capita",  # Sets the title of the bar plot.
  xlab = "Country",  # Labels the x-axis as "Country".
  ylab = "GDP per Capita (USD)"  # Labels the y-axis as "GDP per Capita (USD)".
)

# Add a custom y-axis
axis(
  2,  # Specifies the y-axis.
  at = seq(0, max(myDF$`Country GDP per Capita`), by = 2000),  # Adds tick marks at intervals of 2000 up to the max GDP value.
  las = 1  # Ensures the y-axis labels are horizontal.
)

# Notes on GDP and crash distribution
# 82.7% of commercial airplane crashes occurred in countries with a GDP per Capita of less than 20,000 USD.
# 62% of commercial airplane crashes occurred in countries with a GDP per Capita of less than 10,000 USD.
# 51.7% of commercial airplane crashes occurred in countries with a GDP per Capita of less than 5,000 USD.

"""The resulting bar plot visualizes the GDP per Capita of each country in the dataset, with countries labeled on the x-axis and GDP values on the y-axis. The y-axis is customized to show tick marks at intervals of 2000 USD for better clarity.

Additionally, the analysis highlights the following key insights:

82.7% of commercial airplane crashes occurred in countries with a GDP per Capita of less than 20,000 USD.
62% of commercial airplane crashes occurred in countries with a GDP per Capita of less than 10,000 USD.
51.7% of commercial airplane crashes occurred in countries with a GDP per Capita of less than 5,000 USD.
These insights indicate a strong correlation between lower GDP per Capita and higher occurrences of plane crashes, potentially pointing to differences in infrastructure, aviation safety standards, or operational practices. This visualization effectively combines numerical data and contextual insights for a comprehensive analysis.
"""